### ISSUE TITLE
Problems with picture on home page

### ISSUE THREAD

**Issue by dbqeo** [mvrt-115/MVRT_Site#146]
It works normally on first load and when refreshing, but fails when clicking the logo on the top left.

Occurs in Chrome and Edge.

**Comment by BenCuan** [comment]
Screenshot
![mvrt bug](https://cloud.githubusercontent.com/assets/15005763/12341653/09ac38e2-bad8-11e5-88b0-da82a5dd296a.png)

**Comment by akalari** [comment]
That is a problem with caching. Try force refresh

**Comment by BenCuan** [comment]
Force refresh fixes it temporarily; clicking the logo breaks it again.

**Comment by akalari** [comment]
Hi Ben,

Could you look into this? This is caused by the way the browsers cache things, so if you could figure out a way to redraw this front page by force when the page loads, that would solve the problem. I solved this in Safari, look at app/assets/js/forceredraw.js for the file you should write the redraw in. Also check index.html and the onload element in the body tag.

**Comment by akhil99** [comment]
No longer relevant, as we've reverted to the old/stable site.
